// i18n codegen: crates/sshub/src/i18n/strings.json → .../generated.rs
//
// 실행(레포 루트에서): bun scripts/gen_i18n.mjs
//
// 문자열을 고칠 때는 strings.json만 고치고 이 스크립트를 다시 돌린다.
// 세 언어를 한 곳에 모아 둔 이유는 하나만 빠뜨리는 사고를 막기 위해서다
// (검증에서 걸리고, 생성된 enum 덕에 누락은 컴파일 에러가 된다).
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dest = join(root, 'crates/sshub/src/i18n/generated.rs')
const source = join(root, 'crates/sshub/src/i18n/strings.json')

const strings = JSON.parse(readFileSync(source, 'utf8'))
const keys = Object.keys(strings)

const LANGS = ['ko', 'en', 'ja']
for (const [key, value] of Object.entries(strings)) {
  for (const lang of LANGS) {
    if (typeof value[lang] !== 'string') {
      throw new Error(`${key}: ${lang} 번역이 없습니다`)
    }
  }
}

const variant = (k) =>
  k.split(/[.\-_]/).map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join('')

const esc = (s) =>
  s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')

let out = `// @generated by scripts/gen_i18n.mjs — 직접 수정 금지.
// 원본: crates/sshub/src/i18n/strings.json (${keys.length} keys × ko/en/ja)
#![allow(clippy::too_many_lines)]

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Lang {
    Ko,
    En,
    Ja,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum TrKey {
`
for (const k of keys) out += `    /// ${k}\n    ${variant(k)},\n`
out += `}\n\npub const fn tr(lang: Lang, key: TrKey) -> &'static str {\n    match lang {\n`
for (const lang of ['Ko', 'En', 'Ja']) {
  out += `        Lang::${lang} => match key {\n`
  for (const k of keys) out += `            TrKey::${variant(k)} => "${esc(strings[k][lang.toLowerCase()])}",\n`
  out += `        },\n`
}
out += `    }\n}\n`

writeFileSync(dest, out)
console.log(`ok: ${keys.length} keys → ${dest}`)
