// 1회성 codegen: src/i18n/index.ts → rust/crates/sshub/src/i18n/generated.rs
// 실행: bun rust/scripts/gen_i18n.mjs   (레포 루트에서)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '../..')
const src = readFileSync(join(root, 'src/i18n/index.ts'), 'utf8')

function extractDict(name) {
  const marker = `const ${name}: Dict = {`
  const start = src.indexOf(marker)
  if (start < 0) throw new Error(`dict not found: ${name}`)
  let i = start + marker.length - 1, depth = 0
  for (; i < src.length; i++) {
    if (src[i] === '{') depth++
    else if (src[i] === '}') { depth--; if (depth === 0) break }
  }
  const objText = src.slice(start + marker.length - 1, i + 1)
  return new Function('return ' + objText)()
}

const en = extractDict('en')
const ko = extractDict('ko')
const ja = extractDict('ja')

const keys = Object.keys(en)
for (const [lang, d] of [['ko', ko], ['ja', ja]]) {
  const missing = keys.filter((k) => !(k in d))
  const extra = Object.keys(d).filter((k) => !(k in en))
  if (missing.length || extra.length)
    throw new Error(`${lang} mismatch — missing: ${missing} extra: ${extra}`)
}

const variant = (k) =>
  k.split(/[.\-_]/).map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join('')

const esc = (s) =>
  s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')

let out = `// @generated by rust/scripts/gen_i18n.mjs — 직접 수정 금지.
// 원본: src/i18n/index.ts (${keys.length} keys × ko/en/ja)
#![allow(clippy::too_many_lines)]

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Lang {
    Ko,
    En,
    Ja,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum TrKey {
`
for (const k of keys) out += `    /// ${k}\n    ${variant(k)},\n`
out += `}\n\npub const fn tr(lang: Lang, key: TrKey) -> &'static str {\n    match lang {\n`
for (const [l, d] of [['Ko', ko], ['En', en], ['Ja', ja]]) {
  out += `        Lang::${l} => match key {\n`
  for (const k of keys) out += `            TrKey::${variant(k)} => "${esc(d[k])}",\n`
  out += `        },\n`
}
out += `    }\n}\n`

const dest = join(root, 'rust/crates/sshub/src/i18n/generated.rs')
mkdirSync(dirname(dest), { recursive: true })
writeFileSync(dest, out)
console.log(`ok: ${keys.length} keys → ${dest}`)
