// @generated by rust/scripts/gen_i18n.mjs — 직접 수정 금지.
// 원본: src/i18n/index.ts (192 keys × ko/en/ja)
#![allow(clippy::too_many_lines)]

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Lang {
    Ko,
    En,
    Ja,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum TrKey {
    /// nav.dashboard
    NavDashboard,
    /// nav.servers
    NavServers,
    /// nav.terminal
    NavTerminal,
    /// nav.keys
    NavKeys,
    /// nav.settings
    NavSettings,
    /// sidebar.collapse
    SidebarCollapse,
    /// sidebar.expand
    SidebarExpand,
    /// common.addServer
    CommonAddServer,
    /// common.cancel
    CommonCancel,
    /// common.save
    CommonSave,
    /// common.saving
    CommonSaving,
    /// common.loading
    CommonLoading,
    /// common.connect
    CommonConnect,
    /// common.edit
    CommonEdit,
    /// common.delete
    CommonDelete,
    /// common.favorite
    CommonFavorite,
    /// common.import
    CommonImport,
    /// common.importing
    CommonImporting,
    /// common.export
    CommonExport,
    /// common.confirm
    CommonConfirm,
    /// error.title
    ErrorTitle,
    /// error.message
    ErrorMessage,
    /// error.reload
    ErrorReload,
    /// dashboard.newServer
    DashboardNewServer,
    /// dashboard.emptyHint
    DashboardEmptyHint,
    /// dashboard.addServerCta
    DashboardAddServerCta,
    /// list.subtitle
    ListSubtitle,
    /// list.allGroups
    ListAllGroups,
    /// list.emptyHintNoServers
    ListEmptyHintNoServers,
    /// list.emptyHintNoMatch
    ListEmptyHintNoMatch,
    /// list.confirmDelete
    ListConfirmDelete,
    /// list.confirmDeleteTitle
    ListConfirmDeleteTitle,
    /// edit.name
    EditName,
    /// edit.group
    EditGroup,
    /// edit.groupPlaceholder
    EditGroupPlaceholder,
    /// edit.host
    EditHost,
    /// edit.hostPlaceholder
    EditHostPlaceholder,
    /// edit.port
    EditPort,
    /// edit.user
    EditUser,
    /// edit.userPlaceholder
    EditUserPlaceholder,
    /// edit.authType
    EditAuthType,
    /// edit.authKey
    EditAuthKey,
    /// edit.authPassword
    EditAuthPassword,
    /// edit.authPem
    EditAuthPem,
    /// edit.keySelect
    EditKeySelect,
    /// edit.keyDefault
    EditKeyDefault,
    /// edit.keyHint
    EditKeyHint,
    /// edit.passwordHint
    EditPasswordHint,
    /// edit.pemLabel
    EditPemLabel,
    /// edit.pemHint
    EditPemHint,
    /// edit.pemKeptHint
    EditPemKeptHint,
    /// edit.authAgent
    EditAuthAgent,
    /// edit.agentHint
    EditAgentHint,
    /// edit.proxyJump
    EditProxyJump,
    /// edit.proxyJumpHint
    EditProxyJumpHint,
    /// edit.tags
    EditTags,
    /// edit.tagsPlaceholder
    EditTagsPlaceholder,
    /// edit.notes
    EditNotes,
    /// edit.errName
    EditErrName,
    /// edit.errHost
    EditErrHost,
    /// edit.errUser
    EditErrUser,
    /// edit.errPortInt
    EditErrPortInt,
    /// edit.errPortMin
    EditErrPortMin,
    /// edit.errPortMax
    EditErrPortMax,
    /// keys.subtitle
    KeysSubtitle,
    /// keys.create
    KeysCreate,
    /// keys.import
    KeysImport,
    /// keys.empty
    KeysEmpty,
    /// keys.missingBadge
    KeysMissingBadge,
    /// keys.missingTitle
    KeysMissingTitle,
    /// keys.publicKey
    KeysPublicKey,
    /// keys.createTitle
    KeysCreateTitle,
    /// keys.name
    KeysName,
    /// keys.namePlaceholderCreate
    KeysNamePlaceholderCreate,
    /// keys.createNameHint
    KeysCreateNameHint,
    /// keys.keyType
    KeysKeyType,
    /// keys.ed25519Rec
    KeysEd25519Rec,
    /// keys.keySize
    KeysKeySize,
    /// keys.passphraseOpt
    KeysPassphraseOpt,
    /// keys.passphraseCreatePlaceholder
    KeysPassphraseCreatePlaceholder,
    /// keys.creating
    KeysCreating,
    /// keys.importTitle
    KeysImportTitle,
    /// keys.loadFromFile
    KeysLoadFromFile,
    /// keys.loadFromFileHint
    KeysLoadFromFileHint,
    /// keys.dialogPickTitle
    KeysDialogPickTitle,
    /// keys.loadError
    KeysLoadError,
    /// keys.namePlaceholderImport
    KeysNamePlaceholderImport,
    /// keys.publicKeyLabel
    KeysPublicKeyLabel,
    /// keys.publicKeyOptHint
    KeysPublicKeyOptHint,
    /// keys.derivePub
    KeysDerivePub,
    /// keys.deriving
    KeysDeriving,
    /// keys.importTypeNote
    KeysImportTypeNote,
    /// keys.privateKeyOpt
    KeysPrivateKeyOpt,
    /// keys.privateKeyHint
    KeysPrivateKeyHint,
    /// keys.editTitle
    KeysEditTitle,
    /// keys.edit
    KeysEdit,
    /// keys.replacePrivateOpt
    KeysReplacePrivateOpt,
    /// keys.replacePrivateHint
    KeysReplacePrivateHint,
    /// keys.replacePrivatePlaceholder
    KeysReplacePrivatePlaceholder,
    /// keys.changePassphrase
    KeysChangePassphrase,
    /// keys.currentPassphrase
    KeysCurrentPassphrase,
    /// keys.newPassphrase
    KeysNewPassphrase,
    /// keys.changePassphraseBtn
    KeysChangePassphraseBtn,
    /// keys.changing
    KeysChanging,
    /// keys.passphraseChanged
    KeysPassphraseChanged,
    /// keys.passphraseImportPlaceholder
    KeysPassphraseImportPlaceholder,
    /// keys.importing
    KeysImporting,
    /// keys.confirmDelete
    KeysConfirmDelete,
    /// keys.confirmDeleteTitle
    KeysConfirmDeleteTitle,
    /// term.local
    TermLocal,
    /// term.newLocalTitle
    TermNewLocalTitle,
    /// term.splitRightTitle
    TermSplitRightTitle,
    /// term.splitDownTitle
    TermSplitDownTitle,
    /// term.newConnection
    TermNewConnection,
    /// term.pickNewTab
    TermPickNewTab,
    /// term.pickSplitRight
    TermPickSplitRight,
    /// term.pickSplitDown
    TermPickSplitDown,
    /// term.noServers
    TermNoServers,
    /// term.searchPlaceholder
    TermSearchPlaceholder,
    /// term.searchNext
    TermSearchNext,
    /// term.searchPrev
    TermSearchPrev,
    /// term.closedNotice
    TermClosedNotice,
    /// term.connectFail
    TermConnectFail,
    /// term.reconnect
    TermReconnect,
    /// term.closeTab
    TermCloseTab,
    /// term.closeOthers
    TermCloseOthers,
    /// term.closeRight
    TermCloseRight,
    /// term.confirmCloseTab
    TermConfirmCloseTab,
    /// term.confirmCloseOthers
    TermConfirmCloseOthers,
    /// term.confirmCloseRight
    TermConfirmCloseRight,
    /// term.confirmCloseTitle
    TermConfirmCloseTitle,
    /// term.confirmCloseAction
    TermConfirmCloseAction,
    /// term.broadcast
    TermBroadcast,
    /// common.close
    CommonClose,
    /// term.emptyHint
    TermEmptyHint,
    /// settings.syncDesc
    SettingsSyncDesc,
    /// settings.toConfigTitle
    SettingsToConfigTitle,
    /// settings.toConfigDesc
    SettingsToConfigDesc,
    /// settings.fromConfigTitle
    SettingsFromConfigTitle,
    /// settings.fromConfigDesc
    SettingsFromConfigDesc,
    /// settings.sync
    SettingsSync,
    /// settings.syncing
    SettingsSyncing,
    /// settings.syncToDone
    SettingsSyncToDone,
    /// settings.syncToFail
    SettingsSyncToFail,
    /// settings.importFromConfigDone
    SettingsImportFromConfigDone,
    /// settings.importFromConfigNone
    SettingsImportFromConfigNone,
    /// settings.importFail
    SettingsImportFail,
    /// settings.backupDesc
    SettingsBackupDesc,
    /// settings.exportDesc
    SettingsExportDesc,
    /// settings.importDesc
    SettingsImportDesc,
    /// settings.exportDialogTitle
    SettingsExportDialogTitle,
    /// settings.importDialogTitle
    SettingsImportDialogTitle,
    /// settings.exportDone
    SettingsExportDone,
    /// settings.exportFail
    SettingsExportFail,
    /// settings.importDone
    SettingsImportDone,
    /// settings.phosphorTitle
    SettingsPhosphorTitle,
    /// settings.phosphorDesc
    SettingsPhosphorDesc,
    /// settings.language
    SettingsLanguage,
    /// settings.languageDesc
    SettingsLanguageDesc,
    /// settings.startMenu
    SettingsStartMenu,
    /// settings.startMenuDesc
    SettingsStartMenuDesc,
    /// settings.exportWithKeys
    SettingsExportWithKeys,
    /// settings.exportWithKeysDesc
    SettingsExportWithKeysDesc,
    /// settings.passphrase
    SettingsPassphrase,
    /// settings.passphraseExportHint
    SettingsPassphraseExportHint,
    /// settings.passphraseImportHint
    SettingsPassphraseImportHint,
    /// settings.decrypt
    SettingsDecrypt,
    /// settings.exportEncryptedDone
    SettingsExportEncryptedDone,
    /// settings.shortcutsDesc
    SettingsShortcutsDesc,
    /// settings.pressKeys
    SettingsPressKeys,
    /// settings.exportSelectTitle
    SettingsExportSelectTitle,
    /// settings.selectAll
    SettingsSelectAll,
    /// settings.includeShortcuts
    SettingsIncludeShortcuts,
    /// settings.accent
    SettingsAccent,
    /// settings.bgTone
    SettingsBgTone,
    /// settings.termColors
    SettingsTermColors,
    /// settings.termFontSize
    SettingsTermFontSize,
    /// settings.termFg
    SettingsTermFg,
    /// settings.termBg
    SettingsTermBg,
    /// settings.uiOpacity
    SettingsUiOpacity,
    /// settings.custom
    SettingsCustom,
    /// shortcut.newTab
    ShortcutNewTab,
    /// shortcut.closePane
    ShortcutClosePane,
    /// shortcut.splitRight
    ShortcutSplitRight,
    /// shortcut.splitDown
    ShortcutSplitDown,
    /// shortcut.broadcast
    ShortcutBroadcast,
    /// shortcut.fontIncrease
    ShortcutFontIncrease,
    /// shortcut.fontDecrease
    ShortcutFontDecrease,
    /// shortcut.focusLeft
    ShortcutFocusLeft,
    /// shortcut.focusRight
    ShortcutFocusRight,
    /// shortcut.focusUp
    ShortcutFocusUp,
    /// shortcut.focusDown
    ShortcutFocusDown,
}

pub const fn tr(lang: Lang, key: TrKey) -> &'static str {
    match lang {
        Lang::Ko => match key {
            TrKey::NavDashboard => "대시보드",
            TrKey::NavServers => "서버 목록",
            TrKey::NavTerminal => "터미널",
            TrKey::NavKeys => "SSH 키 관리",
            TrKey::NavSettings => "설정",
            TrKey::SidebarCollapse => "사이드바 접기",
            TrKey::SidebarExpand => "사이드바 펼치기",
            TrKey::CommonAddServer => "서버 추가",
            TrKey::CommonCancel => "취소",
            TrKey::CommonSave => "저장",
            TrKey::CommonSaving => "저장 중...",
            TrKey::CommonLoading => "로딩 중...",
            TrKey::CommonConnect => "연결",
            TrKey::CommonEdit => "편집",
            TrKey::CommonDelete => "삭제",
            TrKey::CommonFavorite => "즐겨찾기",
            TrKey::CommonImport => "가져오기",
            TrKey::CommonImporting => "가져오는 중...",
            TrKey::CommonExport => "내보내기",
            TrKey::CommonConfirm => "확인",
            TrKey::ErrorTitle => "문제가 발생했습니다",
            TrKey::ErrorMessage => "화면을 그리지 못했습니다. 터미널 세션은 그대로 유지되고 있습니다. 다시 불러오면 복구됩니다.",
            TrKey::ErrorReload => "다시 불러오기",
            TrKey::DashboardNewServer => "새 서버",
            TrKey::DashboardEmptyHint => "서버를 추가하거나 설정에서 ~/.ssh/config를 가져오세요.",
            TrKey::DashboardAddServerCta => "서버 추가하기",
            TrKey::ListSubtitle => "~/servers · {n}개 등록됨",
            TrKey::ListAllGroups => "모든 그룹",
            TrKey::ListEmptyHintNoServers => "서버를 추가하거나 설정에서 ~/.ssh/config를 가져오세요.",
            TrKey::ListEmptyHintNoMatch => "다른 검색어를 입력해 보세요.",
            TrKey::ListConfirmDelete => "정말 이 서버를 삭제하시겠습니까?",
            TrKey::ListConfirmDeleteTitle => "서버 삭제",
            TrKey::EditName => "이름",
            TrKey::EditGroup => "그룹",
            TrKey::EditGroupPlaceholder => "예: production",
            TrKey::EditHost => "호스트",
            TrKey::EditHostPlaceholder => "IP 또는 도메인",
            TrKey::EditPort => "포트",
            TrKey::EditUser => "사용자",
            TrKey::EditUserPlaceholder => "예: ec2-user",
            TrKey::EditAuthType => "인증 방식",
            TrKey::EditAuthKey => "SSH 키",
            TrKey::EditAuthPassword => "비밀번호",
            TrKey::EditAuthPem => "PEM",
            TrKey::EditKeySelect => "SSH 키 선택",
            TrKey::EditKeyDefault => "기본 키 사용 (~/.ssh)",
            TrKey::EditKeyHint => "앱에서 생성/가져온 키를 선택하면 연결 시 해당 키(-i)를 사용합니다.",
            TrKey::EditPasswordHint => "비밀번호는 저장되지 않으며, 연결 시 터미널에서 직접 입력합니다.",
            TrKey::EditPemLabel => "PEM 키",
            TrKey::EditPemHint => "JSON 저장소가 아닌 0600 파일에 저장됩니다.",
            TrKey::EditPemKeptHint => "이미 저장된 키가 있습니다 — 비워 두면 유지, 새로 붙여넣으면 교체됩니다.",
            TrKey::EditAuthAgent => "SSH 에이전트",
            TrKey::EditAgentHint => "ssh-agent에 로드된 키(및 기본 키)를 사용합니다.",
            TrKey::EditProxyJump => "점프 호스트 (ProxyJump)",
            TrKey::EditProxyJumpHint => "거쳐갈 배스천(선택, -J). 예: user@bastion 또는 host1,host2.",
            TrKey::EditTags => "태그",
            TrKey::EditTagsPlaceholder => "쉼표로 구분 (예: web, aws)",
            TrKey::EditNotes => "메모",
            TrKey::EditErrName => "이름을 입력하세요",
            TrKey::EditErrHost => "호스트를 입력하세요",
            TrKey::EditErrUser => "사용자를 입력하세요",
            TrKey::EditErrPortInt => "포트는 정수여야 합니다",
            TrKey::EditErrPortMin => "포트는 1 이상이어야 합니다",
            TrKey::EditErrPortMax => "포트는 65535 이하여야 합니다",
            TrKey::KeysSubtitle => "~/.ssh · {n}개",
            TrKey::KeysCreate => "키 생성",
            TrKey::KeysImport => "키 가져오기",
            TrKey::KeysEmpty => "등록된 SSH 키가 없습니다.",
            TrKey::KeysMissingBadge => "개인 키 없음",
            TrKey::KeysMissingTitle => "이 기기에 개인 키 파일이 없습니다. 연결 시 이 키(-i)는 사용되지 않고 기본 인증으로 폴백합니다.",
            TrKey::KeysPublicKey => "공개 키",
            TrKey::KeysCreateTitle => "SSH 키 생성",
            TrKey::KeysName => "이름",
            TrKey::KeysNamePlaceholderCreate => "예: work-laptop",
            TrKey::KeysCreateNameHint => "키 파일은 앱 데이터 폴더의 ssh_keys/에 저장됩니다.",
            TrKey::KeysKeyType => "키 타입",
            TrKey::KeysEd25519Rec => "Ed25519 (권장)",
            TrKey::KeysKeySize => "키 크기",
            TrKey::KeysPassphraseOpt => "Passphrase (선택)",
            TrKey::KeysPassphraseCreatePlaceholder => "비워두면 passphrase 없이 생성",
            TrKey::KeysCreating => "생성 중...",
            TrKey::KeysImportTitle => "SSH 키 가져오기",
            TrKey::KeysLoadFromFile => "파일에서 불러오기",
            TrKey::KeysLoadFromFileHint => "개인 키(단독 .pem 포함) 또는 .pub 파일을 선택하세요. 공개 키가 없으면 자동으로 추출합니다.",
            TrKey::KeysDialogPickTitle => "SSH 키 파일 선택",
            TrKey::KeysLoadError => "파일을 읽지 못했습니다: {err}",
            TrKey::KeysNamePlaceholderImport => "예: legacy-server-key",
            TrKey::KeysPublicKeyLabel => "공개 키 (선택)",
            TrKey::KeysPublicKeyOptHint => "단독 PEM(예: AWS .pem)이면 선택사항입니다. 아래 \"개인 키에서 추출\"로 채울 수 있습니다.",
            TrKey::KeysDerivePub => "개인 키에서 추출",
            TrKey::KeysDeriving => "추출 중…",
            TrKey::KeysImportTypeNote => "가져오기에서 키 타입은 표시용 라벨일 뿐, 실제 접속에는 영향이 없습니다(키 파일을 그대로 사용).",
            TrKey::KeysPrivateKeyOpt => "개인 키 (선택)",
            TrKey::KeysPrivateKeyHint => "입력하면 앱 데이터 폴더의 ssh_keys/에 파일로 저장됩니다.",
            TrKey::KeysEditTitle => "SSH 키 편집",
            TrKey::KeysEdit => "편집",
            TrKey::KeysReplacePrivateOpt => "개인 키 교체 (선택)",
            TrKey::KeysReplacePrivateHint => "비워 두면 기존 개인 키를 그대로 유지합니다.",
            TrKey::KeysReplacePrivatePlaceholder => "••• 저장된 키 유지 — 교체하려면 새 키를 붙여넣으세요",
            TrKey::KeysChangePassphrase => "패스프레이즈 변경",
            TrKey::KeysCurrentPassphrase => "현재 패스프레이즈",
            TrKey::KeysNewPassphrase => "새 패스프레이즈 (비우면 제거)",
            TrKey::KeysChangePassphraseBtn => "패스프레이즈 변경",
            TrKey::KeysChanging => "변경 중…",
            TrKey::KeysPassphraseChanged => "패스프레이즈가 변경되었습니다.",
            TrKey::KeysPassphraseImportPlaceholder => "개인 키에 passphrase가 있다면 입력",
            TrKey::KeysImporting => "가져오는 중...",
            TrKey::KeysConfirmDelete => "{name} 키를 삭제하시겠습니까?",
            TrKey::KeysConfirmDeleteTitle => "키 삭제",
            TrKey::TermLocal => "로컬 터미널",
            TrKey::TermNewLocalTitle => "새 로컬 터미널 (Cmd+T)",
            TrKey::TermSplitRightTitle => "옆으로 분할 (서버/로컬 선택)",
            TrKey::TermSplitDownTitle => "아래로 분할 (서버/로컬 선택)",
            TrKey::TermNewConnection => "새 연결",
            TrKey::TermPickNewTab => "새 탭",
            TrKey::TermPickSplitRight => "옆으로 분할",
            TrKey::TermPickSplitDown => "아래로 분할",
            TrKey::TermNoServers => "등록된 서버 없음",
            TrKey::TermSearchPlaceholder => "검색…",
            TrKey::TermSearchNext => "다음 결과 (Enter)",
            TrKey::TermSearchPrev => "이전 결과 (Shift+Enter)",
            TrKey::TermClosedNotice => "세션이 종료되었습니다. 패널을 닫아주세요.",
            TrKey::TermConnectFail => "연결 실패",
            TrKey::TermReconnect => "재연결",
            TrKey::TermCloseTab => "탭 닫기",
            TrKey::TermCloseOthers => "다른 탭 닫기",
            TrKey::TermCloseRight => "오른쪽 탭 닫기",
            TrKey::TermConfirmCloseTab => "이 탭과 세션을 닫을까요?",
            TrKey::TermConfirmCloseOthers => "다른 탭을 모두 닫을까요?",
            TrKey::TermConfirmCloseRight => "오른쪽 탭을 모두 닫을까요?",
            TrKey::TermConfirmCloseTitle => "탭 닫기",
            TrKey::TermConfirmCloseAction => "닫기",
            TrKey::TermBroadcast => "동시 입력",
            TrKey::CommonClose => "닫기",
            TrKey::TermEmptyHint => "Cmd+T 또는 우측 상단 '새 연결'로 시작하세요. 분할 버튼으로 패널을 나눌 수 있습니다.",
            TrKey::SettingsSyncDesc => "~/.ssh/config 파일과 앱의 서버 목록을 동기화할 수 있습니다.",
            TrKey::SettingsToConfigTitle => "서버 → SSH Config",
            TrKey::SettingsToConfigDesc => "앱의 서버 목록을 ~/.ssh/config에 작성합니다. 기존 파일은 자동 백업됩니다.",
            TrKey::SettingsFromConfigTitle => "SSH Config → 서버",
            TrKey::SettingsFromConfigDesc => "~/.ssh/config에서 서버 정보를 가져와 목록에 추가합니다.",
            TrKey::SettingsSync => "동기화",
            TrKey::SettingsSyncing => "동기화 중...",
            TrKey::SettingsSyncToDone => "서버 목록을 ~/.ssh/config에 동기화했습니다. (기존 파일은 config.bak.<시각>으로 백업)",
            TrKey::SettingsSyncToFail => "동기화 실패: {err}",
            TrKey::SettingsImportFromConfigDone => "{n}개의 새 서버를 가져왔습니다: {names}",
            TrKey::SettingsImportFromConfigNone => "가져올 새 서버가 없습니다. (이미 등록된 이름은 건너뜁니다)",
            TrKey::SettingsImportFail => "가져오기 실패: {err}",
            TrKey::SettingsBackupDesc => "서버 목록을 파일로 내보내고 다른 기기에서 가져옵니다. 비밀 키는 포함되지 않으며, 이름이 같은 항목은 건너뜁니다.",
            TrKey::SettingsExportDesc => "현재 서버·키 목록을 JSON 파일로 저장합니다.",
            TrKey::SettingsImportDesc => "내보낸 JSON 파일을 골라 목록에 병합합니다.",
            TrKey::SettingsExportDialogTitle => "서버 설정 내보내기",
            TrKey::SettingsImportDialogTitle => "서버 설정 가져오기",
            TrKey::SettingsExportDone => "내보내기 완료: {path}",
            TrKey::SettingsExportFail => "내보내기 실패: {err}",
            TrKey::SettingsImportDone => "가져오기 완료 — 서버 +{sa} (건너뜀 {ss}), 키 +{ka} (건너뜀 {ks})",
            TrKey::SettingsPhosphorTitle => "화면 인광색",
            TrKey::SettingsPhosphorDesc => "콘솔 액센트 컬러를 선택합니다.",
            TrKey::SettingsLanguage => "언어",
            TrKey::SettingsLanguageDesc => "인터페이스 언어를 선택합니다. (기본: 시스템)",
            TrKey::SettingsStartMenu => "시작 메뉴",
            TrKey::SettingsStartMenuDesc => "앱을 켤 때 처음 열 메뉴를 선택합니다.",
            TrKey::SettingsExportWithKeys => "키 포함 내보내기",
            TrKey::SettingsExportWithKeysDesc => "개인 키까지 암호로 암호화해 함께 내보냅니다.",
            TrKey::SettingsPassphrase => "암호",
            TrKey::SettingsPassphraseExportHint => "가져올 때 이 암호가 필요합니다.",
            TrKey::SettingsPassphraseImportHint => "이 파일은 암호화되어 있습니다. 암호를 입력하세요.",
            TrKey::SettingsDecrypt => "복호화",
            TrKey::SettingsExportEncryptedDone => "키 포함 암호화 내보내기 완료: {path}",
            TrKey::SettingsShortcutsDesc => "터미널 단축키를 변경합니다. (Cmd+숫자 탭 이동, Cmd+Option+방향키 패널 이동은 고정)",
            TrKey::SettingsPressKeys => "키를 누르세요…",
            TrKey::SettingsExportSelectTitle => "내보낼 항목 선택",
            TrKey::SettingsSelectAll => "전체 선택",
            TrKey::SettingsIncludeShortcuts => "단축키 설정 포함",
            TrKey::SettingsAccent => "강조색",
            TrKey::SettingsBgTone => "배경 톤",
            TrKey::SettingsTermColors => "터미널 색상",
            TrKey::SettingsTermFontSize => "터미널 글자 크기",
            TrKey::SettingsTermFg => "글자색",
            TrKey::SettingsTermBg => "배경색",
            TrKey::SettingsUiOpacity => "UI 투명도",
            TrKey::SettingsCustom => "커스텀",
            TrKey::ShortcutNewTab => "새 탭",
            TrKey::ShortcutClosePane => "패널 닫기",
            TrKey::ShortcutSplitRight => "옆으로 분할",
            TrKey::ShortcutSplitDown => "아래로 분할",
            TrKey::ShortcutBroadcast => "동시 입력 토글",
            TrKey::ShortcutFontIncrease => "글자 크기 키우기",
            TrKey::ShortcutFontDecrease => "글자 크기 줄이기",
            TrKey::ShortcutFocusLeft => "왼쪽 패널로 이동",
            TrKey::ShortcutFocusRight => "오른쪽 패널로 이동",
            TrKey::ShortcutFocusUp => "위쪽 패널로 이동",
            TrKey::ShortcutFocusDown => "아래쪽 패널로 이동",
        },
        Lang::En => match key {
            TrKey::NavDashboard => "Dashboard",
            TrKey::NavServers => "Servers",
            TrKey::NavTerminal => "Terminal",
            TrKey::NavKeys => "SSH Keys",
            TrKey::NavSettings => "Settings",
            TrKey::SidebarCollapse => "Collapse sidebar",
            TrKey::SidebarExpand => "Expand sidebar",
            TrKey::CommonAddServer => "Add Server",
            TrKey::CommonCancel => "Cancel",
            TrKey::CommonSave => "Save",
            TrKey::CommonSaving => "Saving...",
            TrKey::CommonLoading => "Loading...",
            TrKey::CommonConnect => "Connect",
            TrKey::CommonEdit => "Edit",
            TrKey::CommonDelete => "Delete",
            TrKey::CommonFavorite => "Favorite",
            TrKey::CommonImport => "Import",
            TrKey::CommonImporting => "Importing...",
            TrKey::CommonExport => "Export",
            TrKey::CommonConfirm => "Confirm",
            TrKey::ErrorTitle => "Something went wrong",
            TrKey::ErrorMessage => "The screen failed to render. Your terminal sessions are still running. Reload to recover.",
            TrKey::ErrorReload => "Reload",
            TrKey::DashboardNewServer => "New Server",
            TrKey::DashboardEmptyHint => "Add a server, or import ~/.ssh/config from Settings.",
            TrKey::DashboardAddServerCta => "Add a server",
            TrKey::ListSubtitle => "~/servers · {n} registered",
            TrKey::ListAllGroups => "All groups",
            TrKey::ListEmptyHintNoServers => "Add a server, or import ~/.ssh/config from Settings.",
            TrKey::ListEmptyHintNoMatch => "Try a different search term.",
            TrKey::ListConfirmDelete => "Delete this server?",
            TrKey::ListConfirmDeleteTitle => "Delete server",
            TrKey::EditName => "Name",
            TrKey::EditGroup => "Group",
            TrKey::EditGroupPlaceholder => "e.g. production",
            TrKey::EditHost => "Host",
            TrKey::EditHostPlaceholder => "IP or domain",
            TrKey::EditPort => "Port",
            TrKey::EditUser => "User",
            TrKey::EditUserPlaceholder => "e.g. ec2-user",
            TrKey::EditAuthType => "Auth method",
            TrKey::EditAuthKey => "SSH Key",
            TrKey::EditAuthPassword => "Password",
            TrKey::EditAuthPem => "PEM",
            TrKey::EditKeySelect => "SSH key",
            TrKey::EditKeyDefault => "Use default key (~/.ssh)",
            TrKey::EditKeyHint => "Pick a key created/imported here to use it (-i) on connect.",
            TrKey::EditPasswordHint => "Passwords aren't stored; enter it in the terminal on connect.",
            TrKey::EditPemLabel => "PEM key",
            TrKey::EditPemHint => "Stored in a 0600 file outside the JSON store.",
            TrKey::EditPemKeptHint => "A key is already stored — leave empty to keep it, or paste a new one to replace.",
            TrKey::EditAuthAgent => "SSH Agent",
            TrKey::EditAgentHint => "Uses keys loaded in your ssh-agent (and default identities).",
            TrKey::EditProxyJump => "Jump host (ProxyJump)",
            TrKey::EditProxyJumpHint => "Optional bastion to tunnel through (-J), e.g. user@bastion or host1,host2.",
            TrKey::EditTags => "Tags",
            TrKey::EditTagsPlaceholder => "Comma-separated (e.g. web, aws)",
            TrKey::EditNotes => "Notes",
            TrKey::EditErrName => "Enter a name",
            TrKey::EditErrHost => "Enter a host",
            TrKey::EditErrUser => "Enter a user",
            TrKey::EditErrPortInt => "Port must be an integer",
            TrKey::EditErrPortMin => "Port must be 1 or greater",
            TrKey::EditErrPortMax => "Port must be 65535 or less",
            TrKey::KeysSubtitle => "~/.ssh · {n} keys",
            TrKey::KeysCreate => "Create Key",
            TrKey::KeysImport => "Import Key",
            TrKey::KeysEmpty => "No SSH keys yet.",
            TrKey::KeysMissingBadge => "No private key",
            TrKey::KeysMissingTitle => "The private key file isn't on this machine; this key (-i) won't be used and ssh falls back to default auth.",
            TrKey::KeysPublicKey => "Public key",
            TrKey::KeysCreateTitle => "Create SSH Key",
            TrKey::KeysName => "Name",
            TrKey::KeysNamePlaceholderCreate => "e.g. work-laptop",
            TrKey::KeysCreateNameHint => "The key file is saved to the app's ssh_keys/ folder.",
            TrKey::KeysKeyType => "Key type",
            TrKey::KeysEd25519Rec => "Ed25519 (recommended)",
            TrKey::KeysKeySize => "Key size",
            TrKey::KeysPassphraseOpt => "Passphrase (optional)",
            TrKey::KeysPassphraseCreatePlaceholder => "Leave empty for no passphrase",
            TrKey::KeysCreating => "Creating...",
            TrKey::KeysImportTitle => "Import SSH Key",
            TrKey::KeysLoadFromFile => "Load from file",
            TrKey::KeysLoadFromFileHint => "Pick a private key (incl. a bare .pem) or .pub file. The public key is derived when missing.",
            TrKey::KeysDialogPickTitle => "Select SSH key file",
            TrKey::KeysLoadError => "Could not read file: {err}",
            TrKey::KeysNamePlaceholderImport => "e.g. legacy-server-key",
            TrKey::KeysPublicKeyLabel => "Public key (optional)",
            TrKey::KeysPublicKeyOptHint => "Optional for a bare PEM (e.g. AWS .pem). Use \"Derive public key\" below to fill it.",
            TrKey::KeysDerivePub => "Derive public key",
            TrKey::KeysDeriving => "Deriving…",
            TrKey::KeysImportTypeNote => "On import the key type is just a label — it doesn't affect connecting (the key file is used as-is).",
            TrKey::KeysPrivateKeyOpt => "Private key (optional)",
            TrKey::KeysPrivateKeyHint => "If provided, it's saved to the app's ssh_keys/ folder.",
            TrKey::KeysEditTitle => "Edit SSH Key",
            TrKey::KeysEdit => "Edit",
            TrKey::KeysReplacePrivateOpt => "Replace private key (optional)",
            TrKey::KeysReplacePrivateHint => "Leave empty to keep the current private key.",
            TrKey::KeysReplacePrivatePlaceholder => "••• stored key kept — paste a new key to replace",
            TrKey::KeysChangePassphrase => "Change passphrase",
            TrKey::KeysCurrentPassphrase => "Current passphrase",
            TrKey::KeysNewPassphrase => "New passphrase (empty to remove)",
            TrKey::KeysChangePassphraseBtn => "Change passphrase",
            TrKey::KeysChanging => "Changing…",
            TrKey::KeysPassphraseChanged => "Passphrase updated.",
            TrKey::KeysPassphraseImportPlaceholder => "Enter passphrase if the key has one",
            TrKey::KeysImporting => "Importing...",
            TrKey::KeysConfirmDelete => "Delete key \"{name}\"?",
            TrKey::KeysConfirmDeleteTitle => "Delete key",
            TrKey::TermLocal => "Local terminal",
            TrKey::TermNewLocalTitle => "New local terminal (Cmd+T)",
            TrKey::TermSplitRightTitle => "Split right (pick server/local)",
            TrKey::TermSplitDownTitle => "Split down (pick server/local)",
            TrKey::TermNewConnection => "New connection",
            TrKey::TermPickNewTab => "New tab",
            TrKey::TermPickSplitRight => "Split right",
            TrKey::TermPickSplitDown => "Split down",
            TrKey::TermNoServers => "No servers",
            TrKey::TermSearchPlaceholder => "Search…",
            TrKey::TermSearchNext => "Next match (Enter)",
            TrKey::TermSearchPrev => "Previous match (Shift+Enter)",
            TrKey::TermClosedNotice => "Session ended. Close this pane.",
            TrKey::TermConnectFail => "Connection failed",
            TrKey::TermReconnect => "Reconnect",
            TrKey::TermCloseTab => "Close tab",
            TrKey::TermCloseOthers => "Close other tabs",
            TrKey::TermCloseRight => "Close tabs to the right",
            TrKey::TermConfirmCloseTab => "Close this tab and end its session(s)?",
            TrKey::TermConfirmCloseOthers => "Close all other tabs?",
            TrKey::TermConfirmCloseRight => "Close all tabs to the right?",
            TrKey::TermConfirmCloseTitle => "Close tab",
            TrKey::TermConfirmCloseAction => "Close",
            TrKey::TermBroadcast => "Broadcast input",
            TrKey::CommonClose => "Close",
            TrKey::TermEmptyHint => "Start with Cmd+T or 'New connection' (top right). Use the split buttons to divide panes.",
            TrKey::SettingsSyncDesc => "Sync your server list with the ~/.ssh/config file.",
            TrKey::SettingsToConfigTitle => "Servers → SSH Config",
            TrKey::SettingsToConfigDesc => "Writes the app's server list to ~/.ssh/config. The existing file is backed up automatically.",
            TrKey::SettingsFromConfigTitle => "SSH Config → Servers",
            TrKey::SettingsFromConfigDesc => "Imports servers from ~/.ssh/config into the list.",
            TrKey::SettingsSync => "Sync",
            TrKey::SettingsSyncing => "Syncing...",
            TrKey::SettingsSyncToDone => "Synced the server list to ~/.ssh/config. (existing file backed up as config.bak.<time>)",
            TrKey::SettingsSyncToFail => "Sync failed: {err}",
            TrKey::SettingsImportFromConfigDone => "Imported {n} new servers: {names}",
            TrKey::SettingsImportFromConfigNone => "No new servers to import. (existing names are skipped)",
            TrKey::SettingsImportFail => "Import failed: {err}",
            TrKey::SettingsBackupDesc => "Export the server list to a file and import it on another machine. Secrets aren't included; matching names are skipped.",
            TrKey::SettingsExportDesc => "Save the current server/key list as a JSON file.",
            TrKey::SettingsImportDesc => "Pick an exported JSON file to merge into the list.",
            TrKey::SettingsExportDialogTitle => "Export server settings",
            TrKey::SettingsImportDialogTitle => "Import server settings",
            TrKey::SettingsExportDone => "Exported: {path}",
            TrKey::SettingsExportFail => "Export failed: {err}",
            TrKey::SettingsImportDone => "Imported — servers +{sa} (skipped {ss}), keys +{ka} (skipped {ks})",
            TrKey::SettingsPhosphorTitle => "Phosphor color",
            TrKey::SettingsPhosphorDesc => "Choose the console accent color.",
            TrKey::SettingsLanguage => "Language",
            TrKey::SettingsLanguageDesc => "Choose the interface language. (default: system)",
            TrKey::SettingsStartMenu => "Start menu",
            TrKey::SettingsStartMenuDesc => "Which menu opens when the app launches.",
            TrKey::SettingsExportWithKeys => "Export with keys",
            TrKey::SettingsExportWithKeysDesc => "Includes private keys, encrypted with a passphrase.",
            TrKey::SettingsPassphrase => "Passphrase",
            TrKey::SettingsPassphraseExportHint => "You'll need this passphrase to import.",
            TrKey::SettingsPassphraseImportHint => "This file is encrypted. Enter the passphrase.",
            TrKey::SettingsDecrypt => "Decrypt",
            TrKey::SettingsExportEncryptedDone => "Encrypted export (with keys): {path}",
            TrKey::SettingsShortcutsDesc => "Customize terminal shortcuts. (Cmd+digit to switch tabs, Cmd+Option+Arrow to move between panes are fixed)",
            TrKey::SettingsPressKeys => "Press keys…",
            TrKey::SettingsExportSelectTitle => "Select items to export",
            TrKey::SettingsSelectAll => "Select all",
            TrKey::SettingsIncludeShortcuts => "Include shortcuts",
            TrKey::SettingsAccent => "Accent color",
            TrKey::SettingsBgTone => "Background",
            TrKey::SettingsTermColors => "Terminal colors",
            TrKey::SettingsTermFontSize => "Terminal font size",
            TrKey::SettingsTermFg => "Text",
            TrKey::SettingsTermBg => "Background",
            TrKey::SettingsUiOpacity => "UI translucency",
            TrKey::SettingsCustom => "Custom",
            TrKey::ShortcutNewTab => "New tab",
            TrKey::ShortcutClosePane => "Close pane",
            TrKey::ShortcutSplitRight => "Split right",
            TrKey::ShortcutSplitDown => "Split down",
            TrKey::ShortcutBroadcast => "Toggle broadcast input",
            TrKey::ShortcutFontIncrease => "Increase font size",
            TrKey::ShortcutFontDecrease => "Decrease font size",
            TrKey::ShortcutFocusLeft => "Focus pane left",
            TrKey::ShortcutFocusRight => "Focus pane right",
            TrKey::ShortcutFocusUp => "Focus pane up",
            TrKey::ShortcutFocusDown => "Focus pane down",
        },
        Lang::Ja => match key {
            TrKey::NavDashboard => "ダッシュボード",
            TrKey::NavServers => "サーバー一覧",
            TrKey::NavTerminal => "ターミナル",
            TrKey::NavKeys => "SSHキー管理",
            TrKey::NavSettings => "設定",
            TrKey::SidebarCollapse => "サイドバーを折りたたむ",
            TrKey::SidebarExpand => "サイドバーを展開",
            TrKey::CommonAddServer => "サーバー追加",
            TrKey::CommonCancel => "キャンセル",
            TrKey::CommonSave => "保存",
            TrKey::CommonSaving => "保存中...",
            TrKey::CommonLoading => "読み込み中...",
            TrKey::CommonConnect => "接続",
            TrKey::CommonEdit => "編集",
            TrKey::CommonDelete => "削除",
            TrKey::CommonFavorite => "お気に入り",
            TrKey::CommonImport => "インポート",
            TrKey::CommonImporting => "インポート中...",
            TrKey::CommonExport => "エクスポート",
            TrKey::CommonConfirm => "確認",
            TrKey::ErrorTitle => "問題が発生しました",
            TrKey::ErrorMessage => "画面の描画に失敗しました。ターミナルのセッションは維持されています。再読み込みで復帰できます。",
            TrKey::ErrorReload => "再読み込み",
            TrKey::DashboardNewServer => "新規サーバー",
            TrKey::DashboardEmptyHint => "サーバーを追加するか、設定から ~/.ssh/config を取り込んでください。",
            TrKey::DashboardAddServerCta => "サーバーを追加",
            TrKey::ListSubtitle => "~/servers · {n} 件登録",
            TrKey::ListAllGroups => "すべてのグループ",
            TrKey::ListEmptyHintNoServers => "サーバーを追加するか、設定から ~/.ssh/config を取り込んでください。",
            TrKey::ListEmptyHintNoMatch => "別のキーワードで検索してください。",
            TrKey::ListConfirmDelete => "このサーバーを削除しますか？",
            TrKey::ListConfirmDeleteTitle => "サーバー削除",
            TrKey::EditName => "名前",
            TrKey::EditGroup => "グループ",
            TrKey::EditGroupPlaceholder => "例: production",
            TrKey::EditHost => "ホスト",
            TrKey::EditHostPlaceholder => "IPまたはドメイン",
            TrKey::EditPort => "ポート",
            TrKey::EditUser => "ユーザー",
            TrKey::EditUserPlaceholder => "例: ec2-user",
            TrKey::EditAuthType => "認証方式",
            TrKey::EditAuthKey => "SSHキー",
            TrKey::EditAuthPassword => "パスワード",
            TrKey::EditAuthPem => "PEM",
            TrKey::EditKeySelect => "SSHキー選択",
            TrKey::EditKeyDefault => "デフォルトキー (~/.ssh)",
            TrKey::EditKeyHint => "アプリで作成/取り込んだキーを選ぶと、接続時にそのキー(-i)を使用します。",
            TrKey::EditPasswordHint => "パスワードは保存されません。接続時にターミナルで入力します。",
            TrKey::EditPemLabel => "PEMキー",
            TrKey::EditPemHint => "JSONストアではなく 0600 ファイルに保存されます。",
            TrKey::EditPemKeptHint => "既に保存された鍵があります — 空のままで保持、新しく貼り付けると置換します。",
            TrKey::EditAuthAgent => "SSHエージェント",
            TrKey::EditAgentHint => "ssh-agent に読み込まれた鍵（およびデフォルト鍵）を使用します。",
            TrKey::EditProxyJump => "踏み台ホスト (ProxyJump)",
            TrKey::EditProxyJumpHint => "経由する踏み台（任意, -J）。例: user@bastion または host1,host2。",
            TrKey::EditTags => "タグ",
            TrKey::EditTagsPlaceholder => "カンマ区切り (例: web, aws)",
            TrKey::EditNotes => "メモ",
            TrKey::EditErrName => "名前を入力してください",
            TrKey::EditErrHost => "ホストを入力してください",
            TrKey::EditErrUser => "ユーザーを入力してください",
            TrKey::EditErrPortInt => "ポートは整数で入力してください",
            TrKey::EditErrPortMin => "ポートは1以上にしてください",
            TrKey::EditErrPortMax => "ポートは65535以下にしてください",
            TrKey::KeysSubtitle => "~/.ssh · {n} 件",
            TrKey::KeysCreate => "キー作成",
            TrKey::KeysImport => "キーをインポート",
            TrKey::KeysEmpty => "SSHキーがありません。",
            TrKey::KeysMissingBadge => "秘密鍵なし",
            TrKey::KeysMissingTitle => "この端末に秘密鍵ファイルがありません。接続時にこのキー(-i)は使われず、デフォルト認証にフォールバックします。",
            TrKey::KeysPublicKey => "公開鍵",
            TrKey::KeysCreateTitle => "SSHキーを作成",
            TrKey::KeysName => "名前",
            TrKey::KeysNamePlaceholderCreate => "例: work-laptop",
            TrKey::KeysCreateNameHint => "キーファイルはアプリの ssh_keys/ フォルダに保存されます。",
            TrKey::KeysKeyType => "キータイプ",
            TrKey::KeysEd25519Rec => "Ed25519 (推奨)",
            TrKey::KeysKeySize => "キーサイズ",
            TrKey::KeysPassphraseOpt => "パスフレーズ (任意)",
            TrKey::KeysPassphraseCreatePlaceholder => "空欄ならパスフレーズなしで作成",
            TrKey::KeysCreating => "作成中...",
            TrKey::KeysImportTitle => "SSHキーをインポート",
            TrKey::KeysLoadFromFile => "ファイルから読み込む",
            TrKey::KeysLoadFromFileHint => "秘密鍵（単体の .pem を含む）または .pub ファイルを選択します。公開鍵が無ければ自動で抽出します。",
            TrKey::KeysDialogPickTitle => "SSHキーファイルを選択",
            TrKey::KeysLoadError => "ファイルを読み込めませんでした: {err}",
            TrKey::KeysNamePlaceholderImport => "例: legacy-server-key",
            TrKey::KeysPublicKeyLabel => "公開鍵 (任意)",
            TrKey::KeysPublicKeyOptHint => "単体PEM（例: AWS .pem）の場合は任意です。下の「秘密鍵から抽出」で入力できます。",
            TrKey::KeysDerivePub => "秘密鍵から抽出",
            TrKey::KeysDeriving => "抽出中…",
            TrKey::KeysImportTypeNote => "インポート時のキータイプは表示用ラベルで、接続には影響しません（キーファイルをそのまま使用）。",
            TrKey::KeysPrivateKeyOpt => "秘密鍵 (任意)",
            TrKey::KeysPrivateKeyHint => "入力するとアプリの ssh_keys/ フォルダにファイルとして保存されます。",
            TrKey::KeysEditTitle => "SSHキーを編集",
            TrKey::KeysEdit => "編集",
            TrKey::KeysReplacePrivateOpt => "秘密鍵を置き換え (任意)",
            TrKey::KeysReplacePrivateHint => "空のままにすると既存の秘密鍵を保持します。",
            TrKey::KeysReplacePrivatePlaceholder => "••• 保存された鍵を保持 — 置き換えるには新しい鍵を貼り付け",
            TrKey::KeysChangePassphrase => "パスフレーズ変更",
            TrKey::KeysCurrentPassphrase => "現在のパスフレーズ",
            TrKey::KeysNewPassphrase => "新しいパスフレーズ (空で解除)",
            TrKey::KeysChangePassphraseBtn => "パスフレーズを変更",
            TrKey::KeysChanging => "変更中…",
            TrKey::KeysPassphraseChanged => "パスフレーズを変更しました。",
            TrKey::KeysPassphraseImportPlaceholder => "鍵にパスフレーズがあれば入力",
            TrKey::KeysImporting => "インポート中...",
            TrKey::KeysConfirmDelete => "キー「{name}」を削除しますか？",
            TrKey::KeysConfirmDeleteTitle => "キー削除",
            TrKey::TermLocal => "ローカルターミナル",
            TrKey::TermNewLocalTitle => "新規ローカルターミナル (Cmd+T)",
            TrKey::TermSplitRightTitle => "右に分割 (サーバー/ローカル選択)",
            TrKey::TermSplitDownTitle => "下に分割 (サーバー/ローカル選択)",
            TrKey::TermNewConnection => "新規接続",
            TrKey::TermPickNewTab => "新規タブ",
            TrKey::TermPickSplitRight => "右に分割",
            TrKey::TermPickSplitDown => "下に分割",
            TrKey::TermNoServers => "サーバーなし",
            TrKey::TermSearchPlaceholder => "検索…",
            TrKey::TermSearchNext => "次の一致 (Enter)",
            TrKey::TermSearchPrev => "前の一致 (Shift+Enter)",
            TrKey::TermClosedNotice => "セッションが終了しました。パネルを閉じてください。",
            TrKey::TermConnectFail => "接続失敗",
            TrKey::TermReconnect => "再接続",
            TrKey::TermCloseTab => "タブを閉じる",
            TrKey::TermCloseOthers => "他のタブを閉じる",
            TrKey::TermCloseRight => "右側のタブを閉じる",
            TrKey::TermConfirmCloseTab => "このタブとセッションを閉じますか？",
            TrKey::TermConfirmCloseOthers => "他のタブをすべて閉じますか？",
            TrKey::TermConfirmCloseRight => "右側のタブをすべて閉じますか？",
            TrKey::TermConfirmCloseTitle => "タブを閉じる",
            TrKey::TermConfirmCloseAction => "閉じる",
            TrKey::TermBroadcast => "一斉入力",
            TrKey::CommonClose => "閉じる",
            TrKey::TermEmptyHint => "Cmd+T か右上の「新規接続」で開始します。分割ボタンでパネルを分けられます。",
            TrKey::SettingsSyncDesc => "~/.ssh/config ファイルとアプリのサーバー一覧を同期できます。",
            TrKey::SettingsToConfigTitle => "サーバー → SSH Config",
            TrKey::SettingsToConfigDesc => "アプリのサーバー一覧を ~/.ssh/config に書き出します。既存ファイルは自動でバックアップされます。",
            TrKey::SettingsFromConfigTitle => "SSH Config → サーバー",
            TrKey::SettingsFromConfigDesc => "~/.ssh/config からサーバー情報を取り込んで一覧に追加します。",
            TrKey::SettingsSync => "同期",
            TrKey::SettingsSyncing => "同期中...",
            TrKey::SettingsSyncToDone => "サーバー一覧を ~/.ssh/config に同期しました。(既存ファイルは config.bak.<時刻> にバックアップ)",
            TrKey::SettingsSyncToFail => "同期失敗: {err}",
            TrKey::SettingsImportFromConfigDone => "{n} 件の新規サーバーを取り込みました: {names}",
            TrKey::SettingsImportFromConfigNone => "取り込む新規サーバーはありません。(既存の名前はスキップ)",
            TrKey::SettingsImportFail => "インポート失敗: {err}",
            TrKey::SettingsBackupDesc => "サーバー一覧をファイルに書き出し、別の端末で取り込みます。秘密鍵は含まれず、同名の項目はスキップされます。",
            TrKey::SettingsExportDesc => "現在のサーバー・キー一覧をJSONファイルに保存します。",
            TrKey::SettingsImportDesc => "書き出したJSONファイルを選んで一覧にマージします。",
            TrKey::SettingsExportDialogTitle => "サーバー設定をエクスポート",
            TrKey::SettingsImportDialogTitle => "サーバー設定をインポート",
            TrKey::SettingsExportDone => "エクスポート完了: {path}",
            TrKey::SettingsExportFail => "エクスポート失敗: {err}",
            TrKey::SettingsImportDone => "取り込み完了 — サーバー +{sa} (スキップ {ss})、キー +{ka} (スキップ {ks})",
            TrKey::SettingsPhosphorTitle => "発光色",
            TrKey::SettingsPhosphorDesc => "コンソールのアクセントカラーを選択します。",
            TrKey::SettingsLanguage => "言語",
            TrKey::SettingsLanguageDesc => "インターフェース言語を選択します。(既定: システム)",
            TrKey::SettingsStartMenu => "起動メニュー",
            TrKey::SettingsStartMenuDesc => "アプリ起動時に最初に開くメニュー。",
            TrKey::SettingsExportWithKeys => "キーを含めてエクスポート",
            TrKey::SettingsExportWithKeysDesc => "秘密鍵までパスフレーズで暗号化して書き出します。",
            TrKey::SettingsPassphrase => "パスフレーズ",
            TrKey::SettingsPassphraseExportHint => "取り込み時にこのパスフレーズが必要です。",
            TrKey::SettingsPassphraseImportHint => "このファイルは暗号化されています。パスフレーズを入力してください。",
            TrKey::SettingsDecrypt => "復号",
            TrKey::SettingsExportEncryptedDone => "暗号化エクスポート完了（キー含む）: {path}",
            TrKey::SettingsShortcutsDesc => "ターミナルのショートカットを変更します。(Cmd+数字でタブ切替、Cmd+Option+矢印でパネル移動は固定)",
            TrKey::SettingsPressKeys => "キーを押してください…",
            TrKey::SettingsExportSelectTitle => "エクスポートする項目を選択",
            TrKey::SettingsSelectAll => "すべて選択",
            TrKey::SettingsIncludeShortcuts => "ショートカットを含める",
            TrKey::SettingsAccent => "強調色",
            TrKey::SettingsBgTone => "背景トーン",
            TrKey::SettingsTermColors => "ターミナル色",
            TrKey::SettingsTermFontSize => "ターミナル文字サイズ",
            TrKey::SettingsTermFg => "文字色",
            TrKey::SettingsTermBg => "背景色",
            TrKey::SettingsUiOpacity => "UIの透明度",
            TrKey::SettingsCustom => "カスタム",
            TrKey::ShortcutNewTab => "新規タブ",
            TrKey::ShortcutClosePane => "パネルを閉じる",
            TrKey::ShortcutSplitRight => "右に分割",
            TrKey::ShortcutSplitDown => "下に分割",
            TrKey::ShortcutBroadcast => "一斉入力の切替",
            TrKey::ShortcutFontIncrease => "文字サイズを大きく",
            TrKey::ShortcutFontDecrease => "文字サイズを小さく",
            TrKey::ShortcutFocusLeft => "左のパネルへ",
            TrKey::ShortcutFocusRight => "右のパネルへ",
            TrKey::ShortcutFocusUp => "上のパネルへ",
            TrKey::ShortcutFocusDown => "下のパネルへ",
        },
    }
}
